-- Seed data for local development (catalog + discount code).
-- Admin user is created automatically at runtime (see ensureSchema in src/index.tsx).
INSERT OR IGNORE INTO discounts (code, percent, min_books, applies_to, auto_apply, active)
VALUES ('EXTRA20', 20, 2, 'books', 1, 1);

INSERT OR IGNORE INTO products (slug, title, tagline, description, story, price, compare_at, image, gender, category, ages, age_min, age_max, pages, reviews, rating, bestseller, new_release, career, traits_json, active) VALUES
('girls-sticker-pack', 'Girl''s Sticker Pack', 'Personalized sticker packs for your little girl', 'Stickers that celebrate your child’s big dreams — unicorns, rainbows, and her own illustrated face on every sheet.', 'A treasure box of 40+ custom stickers starring your little girl. From unicorns to rainbows, every sheet is illustrated just for her.', 14.99, 29.99, '/static/img/stickers-girl.webp', 'girl', 'sticker', '2–10', 2, 10, 6, 1842, 4.9, 1, 0, 0, '["40+ custom stickers","Her face on every sheet","Premium vinyl"]', 1),
('boys-sticker-pack', 'Boy''s Sticker Pack', 'Personalized sticker packs for your little boy', 'Rockets, dinosaurs, soccer stars — and your boy as the hero of every sticker.', 'A high-energy pack of 40+ custom stickers starring your little boy. Rockets, dinos, race cars, and superheroes — all with his face.', 14.99, 29.99, '/static/img/stickers-boy.webp', 'boy', 'sticker', '2–10', 2, 10, 6, 1604, 4.8, 1, 0, 0, '["40+ custom stickers","His face on every sheet","Premium vinyl"]', 1),
('the-portugals-new-legend', 'The Portugal’s New Legend', 'For champions with red and green at heart', 'Months of sweat and practice in the wind and rain have led to this single moment, the Grand Final for A Seleção das Quinas.', 'Months of sweat and practice in the wind and rain have led to this single moment, the Grand Final for A Seleção das Quinas. Today, with the red and green on their back and the heart of a champion, history is waiting to be made. The whistle is about to blow. Força Portugal! Give them the moment they’ve always dreamed of.', 44.99, NULL, '/static/img/cover-portugal.webp', 'boy', 'book', '6–12', 6, 12, 32, 2924, 4.9, 1, 1, 0, '["Teaches resilience & courage","Upload your favorite photo","Preview before ordering"]', 1),
('princess-girl-the-one-we-all-needed', 'Princess Girl, the One We All Needed', 'A magical journey of kindness and courage', 'When kindness calls, even the smallest acts can change everything.', 'When kindness calls, even the smallest acts can change everything. In this enchanting personalized tale, a Princess follows a glowing guide through gardens, lakes, and stormy skies, helping new friends discover their true strength. Along the way, she learns that bravery and compassion are the brightest magic of all.', 34.99, NULL, '/static/img/cover-princess.webp', 'girl', 'book', '4–10', 4, 10, 32, 2565, 4.9, 1, 1, 0, '["Inspires empathy, courage, and self-belief","32 beautifully illustrated pages","Preview before ordering"]', 1),
('happy-birthday-girl', 'Happy Birthday Girl', 'The perfect birthday gift for your little girl', 'A sparkling birthday adventure where she is the guest of honour — cake, confetti, and a wish that comes true.', 'Today is the most magical day of the year. In this joyful tale, your little girl is the star of her own birthday celebration, complete with friends, cake, and a wish that lights up the sky.', 34.99, NULL, '/static/img/cover-birthday-girl.webp', 'girl', 'book', '2–8', 2, 8, 32, 1180, 4.8, 0, 0, 0, '["Perfect birthday keepsake","Name on every page","Preview before ordering"]', 1),
('happy-birthday-boy', 'Happy Birthday Boy', 'The perfect birthday gift for your little boy', 'Balloons, cake, and a hero’s birthday quest — starring your little boy.', 'The candles are lit and the adventure begins. Your little boy is the birthday hero, racing through a day of surprises, friends, and a wish that comes true.', 34.99, NULL, '/static/img/cover-birthday-boy.webp', 'boy', 'book', '2–8', 2, 8, 32, 980, 4.8, 0, 0, 0, '["Perfect birthday keepsake","Name on every page","Preview before ordering"]', 1),
('super-boy-and-the-dragon', 'Super Boy and the Dragon', 'Kindness turns a scary dragon into a true friend', 'A cape, a roar, and a surprising friendship that proves the bravest heroes lead with kindness.', 'When a lonely dragon frightens the village, Super Boy doesn’t fight — he listens. Together they discover that the bravest magic of all is kindness.', 34.99, NULL, '/static/img/cover-dragon.webp', 'boy', 'book', '4–10', 4, 10, 32, 1432, 4.9, 0, 1, 0, '["Teaches kindness & courage","32 illustrated pages","Preview before ordering"]', 1),
('the-boy-and-the-cosmic-journey', 'The Boy and the Cosmic Journey', 'Discovering courage in an adventure to the stars', 'A bedtime voyage through planets, constellations, and the biggest dream of all.', 'One night a lost star winks at your little boy. He climbs aboard a silver rocket and sails the cosmos, learning that curiosity and courage can light the darkest sky.', 34.99, NULL, '/static/img/cover-cosmic.webp', 'boy', 'book', '4–10', 4, 10, 32, 1210, 4.8, 0, 1, 0, '["Sparks curiosity","32 illustrated pages","Preview before ordering"]', 1),
('princess-and-the-glowing-flower', 'Princess and the Glowing Flower', 'A luminous quest through an enchanted forest', 'A princess follows a petal of light to restore wonder to a fading woodland.', 'Deep in an enchanted forest, a single flower still glows. Your little princess follows its light, helping woodland friends and discovering that hope is something you can carry.', 34.99, NULL, '/static/img/cover-flower.webp', 'girl', 'book', '4–10', 4, 10, 32, 990, 4.8, 0, 0, 0, '["Inspires hope & wonder","32 illustrated pages","Preview before ordering"]', 1),
('girl-counts-with-the-forest-friends', 'Girl Counts with the Forest Friends', 'A gentle counting adventure among woodland animals', 'Rabbits, birds, and foxes help her count from one to ten on a sun-dappled trail.', 'On a walk through the woods, your little girl meets forest friends who need her help counting. One rabbit, two birds, three foxes — every number is a new friend.', 34.99, NULL, '/static/img/cover-forest.webp', 'girl', 'book', '2–6', 2, 6, 28, 760, 4.7, 0, 0, 0, '["Early learning","Counting 1–10","Preview before ordering"]', 1),
('boy-the-dinos-need-you', 'Boy, the Dinos Need You', 'A prehistoric rescue powered by a brave little heart', 'Friendly dinosaurs need a clever helper — and your boy is just the hero.', 'When the dinosaurs lose their favourite valley, your little boy leads a prehistoric rescue. Along the way he learns that even the smallest helper can change everything.', 34.99, NULL, '/static/img/cover-dinos.webp', 'boy', 'book', '2–6', 2, 6, 28, 842, 4.8, 0, 0, 0, '["Dino adventure","Teaches helping others","Preview before ordering"]', 1),
('the-girl-and-the-christmas-express', 'The Girl and the Christmas Express', 'A snowy ride to the North Pole — starring her', 'A glittering steam train, falling snow, and a Christmas wish that needs a conductor.', 'On Christmas Eve a golden train stops at her window. Your little girl becomes the conductor of the Christmas Express, delivering wonder to every snowy village along the way.', 34.99, NULL, '/static/img/cover-christmas.webp', 'girl', 'book', '3–8', 3, 8, 32, 1104, 4.9, 0, 0, 0, '["Holiday keepsake","32 illustrated pages","Preview before ordering"]', 1),
('the-boy-and-the-christmas-express', 'The Boy and the Christmas Express', 'All aboard a snowy Christmas adventure', 'Your little boy takes the whistle of a magical holiday train.', 'A crimson locomotive puffs to his door on Christmas Eve. Your little boy is invited to drive the Christmas Express and discover that giving is the greatest gift.', 34.99, NULL, '/static/img/cover-christmas.webp', 'boy', 'book', '3–8', 3, 8, 32, 1011, 4.8, 0, 0, 0, '["Holiday keepsake","32 illustrated pages","Preview before ordering"]', 1),
('boy-explores-the-zoo', 'Boy Explores the Zoo', 'Wild zoo adventure: meet & learn with animals', 'Giraffes, lions, and penguins — a day at the zoo with your boy as the explorer.', 'A golden ticket, a map, and a day of wonder. Your little boy meets the animals of the zoo and learns that every creature has a story — including him.', 34.99, NULL, '/static/img/cover-zoo.webp', 'boy', 'book', '3–8', 3, 8, 32, 688, 4.7, 0, 0, 0, '["Animal learning","32 illustrated pages","Preview before ordering"]', 1),
('girl-explores-the-zoo', 'Girl Explores the Zoo', 'Wild zoo adventure: meet & learn with animals', 'A curious girl spends a magical day meeting the animals of the zoo.', 'With a sketchbook and a brave heart, your little girl explores the zoo, making friends from the savannah to the arctic exhibit.', 34.99, NULL, '/static/img/cover-zoo.webp', 'girl', 'book', '3–8', 3, 8, 32, 654, 4.7, 0, 0, 0, '["Animal learning","32 illustrated pages","Preview before ordering"]', 1),
('girl-saves-the-arctic-kingdom', 'Girl Saves the Arctic Kingdom', 'An icy adventure powered by care and courage', 'Polar bears, penguins, and a melting kingdom that needs a kind-hearted hero.', 'Far to the north, the Arctic Kingdom is losing its glow. Your little girl sets out across the ice, helping polar friends and proving that care can warm even the coldest world.', 34.99, NULL, '/static/img/cover-arctic.webp', 'girl', 'book', '4–10', 4, 10, 32, 577, 4.8, 0, 0, 0, '["Care & courage","32 illustrated pages","Preview before ordering"]', 1),
('vroom-vroom-the-boy-wins-the-race', 'Vroom Vroom, The Boy Wins the Race', 'A high-speed tale of practice, patience, and victory', 'Helmets on — your little boy is the champion of the grand prix.', 'Practice, patience, and a roaring engine. Your little boy lines up at the starting grid and learns that winning is about never giving up — and cheering for friends too.', 34.99, NULL, '/static/img/cover-race.webp', 'boy', 'book', '3–8', 3, 8, 32, 720, 4.8, 0, 0, 0, '["Sportsmanship","32 illustrated pages","Preview before ordering"]', 1),
('boys-smile', 'Boy''s Smile', 'Discover how a smile can light up every day', 'A gentle story about the superpower hiding in a little boy’s grin.', 'One bright smile can change a rainy morning, a shy friend, and a whole town. Your little boy discovers that kindness starts with the smallest, sunniest thing he owns.', 34.99, NULL, '/static/img/cover-smile.webp', 'boy', 'book', '2–6', 2, 6, 28, 540, 4.9, 0, 0, 0, '["Kindness & joy","28 illustrated pages","Preview before ordering"]', 1),
('princess-weve-been-waiting-for-you', 'Princess! We''ve Been Waiting for You', 'A fairytale welcome written just for her', 'The kingdom has been waiting — and she is the princess they needed all along.', 'Bells ring across the kingdom. Your little girl is the princess they’ve been waiting for, and every page is a celebration of who she already is.', 34.99, NULL, '/static/img/cover-princess.webp', 'girl', 'book', '4–10', 4, 10, 32, 1330, 4.9, 1, 0, 0, '["Fairytale magic","32 illustrated pages","Preview before ordering"]', 1),
('boy-explores-the-world-of-jobs', 'Boy Explores the World of Jobs', 'Open their eyes to the many possibilities waiting for them', 'Firefighter, doctor, pilot, chef — a career adventure starring your little boy.', 'A wonderful, engaging book that opens kids’ eyes to the many possibilities waiting for them. Your little boy tries on the hats of heroes, helpers, and dreamers — and imagines who he might become.', 34.99, NULL, '/static/img/cover-firefighter.webp', 'boy', 'book', '4–10', 4, 10, 32, 890, 4.8, 0, 0, 1, '["Career inspiration","32 illustrated pages","Preview before ordering"]', 1),
('little-firefighter', 'Little Firefighter', 'A career adventure for brave hearts', 'Helmet on, hose ready — your child is the hero of the firehouse.', 'The alarm rings and your child races to the truck. In this hyper-personalised career adventure they learn teamwork, bravery, and how helpers keep a town safe.', 34.99, NULL, '/static/img/cover-firefighter.webp', 'unisex', 'book', '4–10', 4, 10, 32, 612, 4.8, 0, 0, 1, '["Career adventure","Bravery & teamwork","Preview before ordering"]', 1),
('little-police-officer', 'Little Police Officer', 'A career adventure for helpers and protectors', 'Badge shining, your child keeps the neighbourhood kind and safe.', 'With a badge and a kind heart, your child spends a day as a police officer — helping neighbours, finding lost pets, and learning that real heroes listen first.', 34.99, NULL, '/static/img/cover-police.webp', 'unisex', 'book', '4–10', 4, 10, 32, 501, 4.7, 0, 0, 1, '["Career adventure","Kindness & helping","Preview before ordering"]', 1),
('little-pilot', 'Little Pilot', 'A career adventure above the clouds', 'Wheels up — your child takes the controls of a sunrise flight.', 'From the runway to the clouds, your child is the captain. They learn that big dreams take practice, checklists, and a sky full of courage.', 34.99, NULL, '/static/img/cover-pilot.webp', 'unisex', 'book', '4–10', 4, 10, 32, 448, 4.8, 0, 0, 1, '["Career adventure","Dreams & focus","Preview before ordering"]', 1),
('little-doctor', 'Little Doctor', 'A career adventure of care and healing', 'Stethoscope on — your child is the kindest doctor in town.', 'In a colourful children’s clinic, your child listens, helps, and heals. A gentle career story about empathy, science, and looking after others.', 34.99, NULL, '/static/img/cover-doctor.webp', 'unisex', 'book', '4–10', 4, 10, 32, 533, 4.8, 0, 0, 1, '["Career adventure","Empathy & care","Preview before ordering"]', 1);
