-- Seed data for local development: the ORIGINAL demo catalogue.
--
-- V2 Phase 2: every title, tagline, story and cover path below is original
-- content authored for this project (see src/data.ts, which this file mirrors).
-- No reference-catalogue title, story, artwork, review count, rating or
-- endorsement appears here, and `reviews`/`rating` are 0 because no review
-- rows back them (migration 0022 neutralised the legacy invented aggregates).
--
-- Derived rows (per-currency prices, variant prices, collection membership,
-- product facts, media records) are NOT duplicated here: the application's
-- idempotent bootstrap (src/index.tsx::bootstrapLocalDefaults) derives them
-- from these products on the first request, exactly as migrations 0020/0023 do
-- for an existing database. test/unit/phase2-catalogue-seed.test.ts asserts
-- that this file and src/data.ts stay in sync.
INSERT OR IGNORE INTO discounts (code, percent, min_books, applies_to, auto_apply, active)
VALUES ('EXTRA20', 20, 2, 'books', 1, 1);

INSERT OR IGNORE INTO products (slug, title, tagline, description, story, price, compare_at, image, gender, category, ages, age_min, age_max, pages, reviews, rating, bestseller, new_release, career, traits_json, active, price_minor, compare_at_price_minor) VALUES
('the-lantern-and-the-long-night', 'The Lantern and the Long Night', 'A small light carried a long way home', 'A child sets out before dawn with one lantern and a list of neighbours to check on.', 'The night is longer than it should be, and the path home keeps folding back on itself. One lantern, one careful step at a time, and a village that is still awake when the morning finally comes.', 34.99, NULL, '/static/img/art/cover-the-lantern-and-the-long-night.svg', 'girl', 'book', '4–8', 4, 8, 32, 0, 0, 1, 0, 0, '["A quiet bravery story","32 illustrated pages","Review every page before ordering"]', 1, 3499, NULL),
('captain-of-the-cardboard-sea', 'Captain of the Cardboard Sea', 'One box, one ocean, one very serious captain', 'A cardboard box becomes a ship, and the living room becomes open water.', 'The box arrived on Tuesday. By Wednesday it was a ship with a flag, a crew of one, and a horizon that ran from the sofa to the kitchen door.', 34.99, NULL, '/static/img/art/cover-captain-of-the-cardboard-sea.svg', 'unisex', 'book', '3–7', 3, 7, 28, 0, 0, 1, 0, 0, '["Play and imagination","28 illustrated pages","Name and age written into the text"]', 1, 3499, NULL),
('the-quiet-drum', 'The Quiet Drum', 'The loudest sound is the one you keep inside', 'A child who is told to be quieter finds a way to be heard anyway.', 'Everyone says the drum is too loud for the house. So it is practised in secret, softly, until the day the whole street needs a rhythm to walk to.', 34.99, NULL, '/static/img/art/cover-the-quiet-drum.svg', 'unisex', 'book', '4–9', 4, 9, 32, 0, 0, 0, 0, 0, '["Feelings and self-expression","32 illustrated pages","Dedication page included"]', 1, 3499, NULL),
('the-moon-garden', 'The Moon Garden', 'Some flowers only open at night', 'A garden that blooms after dark, and the child who learns to wait for it.', 'By day the garden looks like nothing at all. But when the house is quiet and the moon is up, the white flowers open one by one, and they only open for someone who waits.', 34.99, NULL, '/static/img/art/cover-the-moon-garden.svg', 'girl', 'book', '4–9', 4, 9, 32, 0, 0, 0, 1, 0, '["Patience and wonder","32 illustrated pages","A bedtime pacing that slows down"]', 1, 3499, NULL),
('the-paper-aeroplane-race', 'The Paper Aeroplane Race', 'Fold, aim, and hope the wind agrees', 'Three folds, one throw, and a race across the whole playground.', 'The rules are simple: one sheet of paper, no throwing twice, and whoever lands furthest wins. The wind has other ideas.', 29.99, 34.99, '/static/img/art/cover-the-paper-aeroplane-race.svg', 'boy', 'book', '5–10', 5, 10, 32, 0, 0, 0, 0, 0, '["Trying again after losing","32 illustrated pages","Age range written for 5–10"]', 1, 2999, 3499),
('the-snow-fox', 'The Snow Fox', 'White on white, and a trail worth following', 'A fox crosses a snowfield, and a child follows the tracks to see where they end.', 'The tracks start at the fence and keep going. Behind the ridge the snow is deeper, the air is quieter, and the fox has been waiting to see who was curious enough to follow.', 34.99, NULL, '/static/img/art/cover-the-snow-fox.svg', 'girl', 'book', '3–8', 3, 8, 28, 0, 0, 0, 0, 0, '["Animals and seasons","28 illustrated pages","Short lines for younger readers"]', 1, 3499, NULL),
('the-puddle-who-met-the-sea', 'The Puddle Who Met the Sea', 'A very small amount of water with very large plans', 'A puddle in a gutter is certain it is on its way to the ocean.', 'It rains all morning and the gutter fills. The puddle has heard about the sea from a passing gull, and it is not going to let a drain get in the way.', 29.99, NULL, '/static/img/art/cover-the-puddle-who-met-the-sea.svg', 'unisex', 'book', '3–7', 3, 7, 28, 0, 0, 0, 0, 0, '["Water and weather","28 illustrated pages","Repetition for early readers"]', 1, 2999, NULL),
('the-brave-little-baker', 'The Brave Little Baker', 'The first batch never works. The second one might.', 'A child bakes alone for the first time, and learns what to do when it goes wrong.', 'Flour on the floor, a flat cake, and one more try. The recipe does not mention what to do when your hands are shaking, so the baker works that part out alone.', 29.99, NULL, '/static/img/art/cover-the-brave-little-baker.svg', 'unisex', 'book', '2–5', 2, 5, 24, 0, 0, 0, 0, 0, '["First attempts and mistakes","24 illustrated pages","Very short sentences"]', 1, 2999, NULL),
('the-star-collector', 'The Star Collector', 'A jar, a ladder, and the night sky', 'A child decides to catch a star, and finds out what they are actually made of.', 'The ladder is not tall enough and the jar is not wide enough, so the collector builds a rocket out of an old kettle and a lot of patience.', 39.99, NULL, '/static/img/art/cover-the-star-collector.svg', 'boy', 'book', '5–10', 5, 10, 36, 0, 0, 0, 1, 0, '["Space and curiosity","36 illustrated pages","Longer story arc for 5–10"]', 1, 3999, NULL),
('the-forest-that-sang', 'The Forest That Sang', 'Every tree kept a different note', 'A forest loses its rhythm, and one child puts it back together.', 'The wind used to move through the trees in order: low, then high, then low again. Something has changed, and the forest needs someone to listen carefully enough to fix it.', 34.99, NULL, '/static/img/art/cover-the-forest-that-sang.svg', 'girl', 'book', '4–8', 4, 8, 32, 0, 0, 0, 0, 0, '["Listening and attention","32 illustrated pages","Nature and music themes"]', 1, 3499, NULL),
('the-lost-little-dinosaur', 'The Lost Little Dinosaur', 'Everyone else is bigger. That is not the point.', 'A very small dinosaur is separated from the herd and has to find the way back.', 'The valley is wide and the ferns are tall, and from down here everything looks the same. Being small turns out to be useful when the path is narrow.', 29.99, NULL, '/static/img/art/cover-the-lost-little-dinosaur.svg', 'boy', 'book', '2–6', 2, 6, 24, 0, 0, 0, 0, 0, '["Being small and capable","24 illustrated pages","Simple","repeating refrain"]', 1, 2999, NULL),
('the-great-paper-boat-race', 'The Great Paper Boat Race', 'Down the stream, past the stones, to the bridge', 'Two paper boats race a whole stream, and only one of them is folded well.', 'The stream runs behind the houses and under the bridge. Getting there means surviving the stones, the weeds and one very large puddle.', 29.99, NULL, '/static/img/art/cover-the-great-paper-boat-race.svg', 'unisex', 'book', '4–8', 4, 8, 28, 0, 0, 0, 0, 0, '["Competition and fairness","28 illustrated pages","Follows a single day"]', 1, 2999, NULL),
('the-kind-vet', 'The Kind Vet', 'The animals cannot say what is wrong. So you look closer.', 'A day in a small animal clinic, told from the vet’s own point of view.', 'A nervous dog, a guinea pig with a bad paw, and a cat who has opinions. The work is mostly watching, and then deciding what to do next.', 34.99, NULL, '/static/img/art/cover-the-kind-vet.svg', 'unisex', 'book', '4–9', 4, 9, 32, 0, 0, 0, 0, 1, '["A job shown as real tasks","32 illustrated pages","Caring for animals"]', 1, 3499, NULL),
('the-little-fire-crew', 'The Little Fire Crew', 'Everyone has a job, and the job has a checklist', 'A small fire crew answers three calls in one day, and each one is different.', 'A cat in a tree is not the same as smoke in a kitchen. The crew checks the list, checks each other, and goes.', 34.99, NULL, '/static/img/art/cover-the-little-fire-crew.svg', 'unisex', 'book', '3–7', 3, 7, 28, 0, 0, 0, 0, 1, '["Teamwork and safety","28 illustrated pages","A real day in the job"]', 1, 3499, NULL),
('up-in-the-clouds', 'Up in the Clouds', 'Checklists first. Then the sky.', 'A pilot walks through a full day: checks, take-off, weather, landing.', 'There is a list for everything, and the list is not boring — it is the reason the plane is allowed to leave the ground at all.', 34.99, NULL, '/static/img/art/cover-up-in-the-clouds.svg', 'unisex', 'book', '5–10', 5, 10, 32, 0, 0, 0, 0, 1, '["Preparation and focus","32 illustrated pages","Weather and flight basics"]', 1, 3499, NULL),
('the-helping-hands-clinic', 'The Helping Hands Clinic', 'A clinic where everyone has a different job', 'A child visits a clinic and meets the people who make it work.', 'Reception, records, the nurse who takes the temperature, and the doctor who explains what happens next. Nobody does it alone.', 34.99, NULL, '/static/img/art/cover-the-helping-hands-clinic.svg', 'girl', 'book', '4–9', 4, 9, 32, 0, 0, 0, 0, 1, '["Many roles in one place","32 illustrated pages","Explains a visit step by step"]', 1, 3499, NULL),
('the-bridge-builders', 'The Bridge Builders', 'Measure twice. Then measure again.', 'A team builds a footbridge over a stream, from first sketch to first crossing.', 'The plans are wrong twice before they are right. The bridge does not care about the plans — only about the measurements.', 39.99, NULL, '/static/img/art/cover-the-bridge-builders.svg', 'unisex', 'book', '6–11', 6, 11, 36, 0, 0, 0, 0, 1, '["Engineering and planning","36 illustrated pages","An older","longer read"]', 1, 3999, NULL),
('the-curious-scientist', 'The Curious Scientist', 'A question, a guess, and a test that proves you wrong', 'A child runs three small experiments and reports what actually happened.', 'The guess is the easy part. The test is where the work is, and the answer is allowed to be no.', 39.99, NULL, '/static/img/art/cover-the-curious-scientist.svg', 'unisex', 'book', '5–10', 5, 10, 32, 0, 0, 0, 1, 1, '["Method and honesty","32 illustrated pages","Safe experiments to try at home"]', 1, 3999, NULL),
('the-birthday-balloon', 'The Birthday Balloon', 'One balloon, one gust of wind, one long chase', 'A birthday balloon escapes, and the whole street helps bring it back.', 'It was tied to the gate. Then it was not. Following it means meeting every neighbour on the hill.', 29.99, NULL, '/static/img/art/cover-the-birthday-balloon.svg', 'girl', 'book', '2–6', 2, 6, 24, 0, 0, 0, 0, 0, '["Birthday story","24 illustrated pages","Short and rhythmic"]', 1, 2999, NULL),
('the-snowy-night-parade', 'The Snowy Night Parade', 'Lanterns, boots, and a very slow walk', 'A village walks through the snow together, one lantern at the front.', 'Nobody hurries. The lanterns go first, the boots follow, and the whole street ends up at the same warm doorway.', 34.99, NULL, '/static/img/art/cover-the-snowy-night-parade.svg', 'boy', 'book', '3–8', 3, 8, 28, 0, 0, 0, 0, 0, '["Community and winter","28 illustrated pages","Calm","slow pacing"]', 1, 3499, NULL),
('the-sunrise-kite-club', 'The Sunrise Kite Club', 'Up before the wind, out before the sun', 'A kite club meets at dawn, and the newest member has never flown one.', 'The hill is cold at six in the morning and the kite is not interested. It takes three people, one broken string and a lot of running.', 29.99, NULL, '/static/img/art/cover-the-sunrise-kite-club.svg', 'unisex', 'book', '4–8', 4, 8, 28, 0, 0, 0, 0, 0, '["Perseverance","28 illustrated pages","Wind and weather"]', 1, 2999, NULL),
('the-moonlight-parade', 'The Moonlight Parade', 'The best things happen after bedtime', 'A child who cannot sleep finds a parade going past the window.', 'The drums are very quiet and the lanterns are very small, but the parade is definitely real, and it is definitely waiting for one more marcher.', 34.99, NULL, '/static/img/art/cover-the-moonlight-parade.svg', 'girl', 'book', '3–7', 3, 7, 28, 0, 0, 0, 0, 0, '["Bedtime and imagination","28 illustrated pages","Ends on a quiet note"]', 1, 3499, NULL),
('the-little-explorer', 'The Little Explorer', 'A map drawn from memory, and a woods that keeps changing', 'A child draws a map of the woods and then has to trust it.', 'The path looked simple on paper. In the woods there are three fallen trees, two wrong turns and one very good view.', 29.99, NULL, '/static/img/art/cover-the-little-explorer.svg', 'boy', 'book', '4–8', 4, 8, 28, 0, 0, 0, 0, 0, '["Maps and navigation","28 illustrated pages","Encourages outdoor play"]', 1, 2999, NULL),
('star-sticker-sheet', 'Star Sticker Sheet', 'A whole sheet of stars, with their name on it', 'One sheet of star and sparkle stickers personalised with your child’s name.', 'Twelve stickers on one sheet: stars, bursts and little sparkles, all labelled with the name you chose.', 14.99, 19.99, '/static/img/art/cover-star-sticker-sheet.svg', 'unisex', 'sticker', '2–10', 2, 10, 1, 0, 0, 0, 0, 0, '["One sheet","twelve stickers","Name printed on the sheet","Matte finish"]', 1, 1499, 1999),
('meadow-sticker-sheet', 'Meadow Sticker Sheet', 'Leaves, flowers and small green things', 'One sheet of plant and meadow stickers personalised with your child’s name.', 'Leaves, petals, seed heads and one very determined weed, arranged across a single sheet.', 14.99, NULL, '/static/img/art/cover-meadow-sticker-sheet.svg', 'unisex', 'sticker', '2–10', 2, 10, 1, 0, 0, 0, 0, 0, '["One sheet","twelve stickers","Name printed on the sheet","Matte finish"]', 1, 1499, NULL),
('space-sticker-sheet', 'Space Sticker Sheet', 'Rockets, planets and one quiet moon', 'One sheet of space stickers personalised with your child’s name.', 'A rocket, three planets, a comet and a moon, all on one sheet with their name across the top.', 14.99, NULL, '/static/img/art/cover-space-sticker-sheet.svg', 'unisex', 'sticker', '2–10', 2, 10, 1, 0, 0, 0, 0, 0, '["One sheet","twelve stickers","Name printed on the sheet","Matte finish"]', 1, 1499, NULL),
('ocean-sticker-sheet', 'Ocean Sticker Sheet', 'Waves, shells and something with fins', 'One sheet of ocean stickers personalised with your child’s name.', 'Waves, shells, a whale and a shoal of small fish, arranged across a single sheet.', 14.99, NULL, '/static/img/art/cover-ocean-sticker-sheet.svg', 'unisex', 'sticker', '2–10', 2, 10, 1, 0, 0, 0, 0, 0, '["One sheet","twelve stickers","Name printed on the sheet","Matte finish"]', 1, 1499, NULL);
